apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bs7bpmn2t-nodejs
  janus-idp.io/tekton: bs7bpmn2t-nodejs
  backstage.io/kubernetes-id: bs7bpmn2t-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bs7bpmn2t-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
